# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='abcd', max_length=6)),
                ('start_date', models.DateTimeField(verbose_name='date game started')),
                ('round', models.IntegerField(default='setup')),
                ('phase', models.IntegerField(default='write')),
                ('round_start_date', models.DateTimeField(verbose_name='date round started')),
                ('phase_start_date', models.DateTimeField(verbose_name='date phase started')),
                ('num_players', models.IntegerField(default=0)),
                ('max_num_players', models.IntegerField(default=10)),
                ('max_draw_time', models.IntegerField(default=120)),
                ('max_write_time', models.IntegerField(default=60)),
            ],
        ),
    ]
