# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='great player', max_length=32)),
                ('created_date', models.DateTimeField(verbose_name='date player created')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.Game')),
            ],
        ),
    ]
